# Generated by Django 3.2.6 on 2021-08-30 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(default='', unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='CreateResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crDate', models.DateTimeField(auto_now_add=True)),
                ('crAllow', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responseContent', models.TextField(blank=True)),
                ('responseDate', models.DateTimeField(auto_now_add=True)),
                ('ResponseAllow', models.BooleanField(default=False)),
                ('responseUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTitle', models.CharField(max_length=128)),
                ('postContent', models.TextField(blank=True)),
                ('postDate', models.DateTimeField(auto_now_add=True)),
                ('postCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CallBoard.category')),
                ('postResponse', models.ManyToManyField(through='CallBoard.CreateResponse', to='CallBoard.Response')),
                ('postUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='createresponse',
            name='crPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CallBoard.post'),
        ),
        migrations.AddField(
            model_name='createresponse',
            name='crResponse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CallBoard.response'),
        ),
    ]
