# Generated by Django 3.2.6 on 2021-08-30 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CallBoard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
