# Generated by Django 3.2.6 on 2021-08-31 12:11

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CallBoard', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=froala_editor.fields.FroalaField(blank=True),
        ),
    ]
