# Generated by Django 3.2.6 on 2021-08-31 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CallBoard', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentPost',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='CallBoard.post'),
        ),
    ]
